canonical/craft-application

- .github/workflows/tests.yaml
- pyproject.toml
- tests/integration/test_nothing.py
- tests/unit/test_nothing.py
- tox.ini
> ci: ensure tests succeed in CI

- craft_application/app.py
- craft_application/commands/lifecycle.py
- craft_application/services/lifecycle.py
- tests/conftest.py
- tests/integration/services/test_lifecycle.py
- tests/unit/commands/test_lifecycle.py
- tests/unit/services/test_lifecycle.py
- tests/unit/test_app.py
-----
@cmatsuoka found a case where I'd accidentally marked GPL, but this entire repo is supposed to be LGPL. This fixes those.
> meta: fix GPL references to LGPL

- .github/workflows/docs.yaml
- .github/workflows/tests.yaml
- craft_application/services/provider.py
- pyproject.toml
- tests/unit/services/test_provider.py
> providers: pause the emitter before launching inner instance

- craft_application/commands/lifecycle.py
- craft_application/services/package.py
- tests/conftest.py
- tests/unit/commands/test_lifecycle.py
This avoids needing to early load options
-----
> fix(package service): change signature for pack

- craft_application/application.py
- tests/integration/test_application.py
Removed explicit references to <Application>.project during Application._configure_services to allow for non-lifecycle commands to be used.
-----
This is a workaround for canonical/craft-application#63
> fix: remove compulsory need for project on service configuration

- craft_application/models/base.py
- tests/unit/models/project_models/full_project.yaml
- tests/unit/models/test_project.py
Add a representer as we do for other craft applications to correctly dump multi line strings.
-----
> fix: correctly represent yaml dumped multiline strings

- craft_application/models/base.py
- craft_application/models/project.py
- tests/unit/models/project_models/basic_project.yaml
- tests/unit/models/project_models/full_project.yaml
This follows the expectations for Craft Applications of having name, version, summary and description. Followed by the base/platform data, then closing with the metadatalinks. And finally, parts.
-----
> fix: order the yaml output

- craft_application/application.py
- craft_application/commands/__init__.py
- craft_application/commands/other.py
- tests/integration/test_application.py
- tests/unit/commands/test_other.py
- tests/unit/test_application.py
Implement the `version` command with the same output as the `--version`
command-line option. Project loading is deferred to the point where
managed commands are executed.
Fixes #63
-----
> feat(commands): add version command

- craft_application/services/base.py
- craft_application/services/service_factory.py
- tests/unit/services/test_service_factory.py
Service classes can override the `setup` method to run custom
preparation before service execution, such as downloading additional
assets or performing consistency checks.
-----
> feat(services): add service setup method

- craft_application/application.py
- craft_application/commands/base.py
- craft_application/commands/lifecycle.py
- craft_application/models/__init__.py
- craft_application/models/project.py
- craft_application/services/lifecycle.py
- craft_application/services/provider.py
- craft_application/util/__init__.py
- craft_application/util/platforms.py
- tests/conftest.py
- tests/integration/services/test_lifecycle.py
- tests/integration/services/test_provider.py
- tests/integration/services/test_service_factory.py
- tests/integration/test_application.py
- tests/unit/commands/test_lifecycle.py
- tests/unit/models/test_project.py
- tests/unit/services/test_lifecycle.py
- tests/unit/services/test_provider.py
- tests/unit/test_application.py
Enable multi-artefact builds by using the application-defined build plan
resolver to create multiple provider instances. Further refactoring may
be necessary if applications such as Rockcraft and Charmcraft require
additional features.
Fixes #60
-----
Note
* Passing the target architecture in service creation because instantiating the lifecycle manager in the `run` method proved to be problematic in certain situations, this can be refactored later if needed.
> feat(application): enable build plans

- craft_application/services/lifecycle.py
- tests/conftest.py
- tests/integration/services/test_lifecycle.py
- tests/unit/services/test_lifecycle.py
The previous version of the LifecycleService was initializing the craft-parts lifecycle manager during its __init__(). This is possibly an expensive operation that is better suited for the setup() method.
-----
> refactor: delay creation of LifecycleManager

- craft_application/commands/base.py
- tests/integration/test_application.py
- tests/unit/commands/test_base.py
-----
Fixes #76 
This is further tested in Charmcraft's craft-application pack testing.
> fix(cli): enable per-command help queries

- craft_application/application.py
- craft_application/services/provider.py
- craft_application/util/paths.py
- tests/unit/services/test_provider.py
- tests/unit/util/test_paths.py
One could argue that this a bugfix since this was missing behavior from the existing craft tools. Regardless, this commit updates the instance() method in the default ProviderService to fetch the logfile from inside the build instance once its done. The contents of this file are then emitted so that they can end up in the logs of the "outer" instance.
Fixes #59
-----
> feat: fetch logs from inside the build instance

- craft_application/application.py
- craft_application/commands/base.py
- craft_application/commands/lifecycle.py
- craft_application/services/provider.py
- tests/conftest.py
- tests/integration/conftest.py
- tests/integration/services/test_service_factory.py
- tests/unit/commands/test_base.py
- tests/unit/commands/test_lifecycle.py
- tests/unit/conftest.py
- tests/unit/services/test_provider.py
- tests/unit/services/test_service_factory.py
This pull request has 3 commits because I had to do some refactoring on `AppCommand` to get this "hybrid" command to work:
- The first commit adds `ProviderService.clean_instances()`;
- The second commit refactors `AppCommand.run_managed` from a property to a regular method that receives the parsed cli arguments;
- The third commit hooks the first two by updating the `clean` command to call either `provider.clean_instances()` or `lifecycle.clean()` depending on the command line args.
Fixes #56
> fix: clean build provider when no parts are given

- craft_application/application.py
- tests/unit/test_application.py
Capture these errors so they are not treated as internal errors with no details about the error.
-----
Fixes #55
> fix: catch PartsError and ProviderError from dispatch run

- craft_application/application.py
- tests/unit/test_application.py
Instead of default to the installed metadata, first try to use the app's main package (via the standard __version__ attribute), *then* fallback to importlib.metadata, *then* fallback to "dev".
Fixes #90
-----
> fix: more robust determination of the app version

- craft_application/application.py
- tests/integration/test_application.py
- tests/unit/test_application.py
Instead of handling it like an internal error, present the help message as we do in _get_dispatcher() (for e.g. invalid commands) and return the same return code.
Fixes #89
-----
> fix: better help for invalid command args

- craft_application/services/lifecycle.py
- tests/unit/services/test_lifecycle.py
* Add a progress message for the step where the lifecycle is initialised (build-packages, snaps, etc)
* Expose the lifecycle's ProjectInfo, mostly for the sake of tests.
> some minor lifecycle papercuts

- craft_application/__init__.py
- craft_application/application.py
- craft_application/errors.py
- craft_application/secrets.py
- tests/conftest.py
- tests/integration/data/build-secrets/secret-source-folder/source-file.txt
- tests/integration/data/build-secrets/testcraft.yaml
- tests/integration/test_application.py
- tests/unit/test_application.py
- tests/unit/test_secrets.py
The first commit has the code to handle the secrets in yaml data, and the second commit updates the Application to use the first commit's code.
> Support build secrets in destructive mode

- craft_application/commands/lifecycle.py
- tests/integration/data/valid_projects/basic/stderr
- tests/integration/data/valid_projects/basic/stdout
- tests/integration/data/valid_projects/environment/stderr
- tests/integration/data/valid_projects/environment/stdout
- tests/integration/test_application.py
- tests/unit/commands/test_lifecycle.py
Replace the previous "Packing..." message instead of appending to it.
-----
> fix: use progress for the packing messages

- craft_application/application.py
- craft_application/errors.py
- craft_application/secrets.py
- tests/integration/test_application.py
- tests/unit/test_application.py
- tests/unit/test_secrets.py
This is done by encoding the secrets, in the host-application, into the environment of the managed instance. The managed instance then decodes this environment and uses it to re-render the project secrets.
-----
> feat: support build-secrets in managed-mode

- .readthedocs.yaml
I think these came from a template, but the readthedocs build is currently failing from lack of latex and I can't imagine someone would want a pdf/ebook of these docs.
-----
> chore: drop pdf/epub readthedocs build

- pyproject.toml
-----
- Update base compatibility tag from ``base-v2`` to ``base-v3``
This fixes an issue where LXD instances created with
``craft-providers==1.16.0`` may fail to start with
``craft-providers>=1.17.0``.
- Require a disk device in the default LXD profile
- Add Ubuntu 23.10 (Mantic) support
- Check if base instance status before copying
- Fail quickly when LXD errors do not involve instance creation
- Add ``check`` parameter to ``execute_run``
- Use a shared pip cache across instances
- Remove Ubuntu 22.10 (Kinetic) support
- Capture details for snap errors
- Improve LXD instance creation process to avoid race conditions. The base
instance is now created first and copied to an instance. Retry, timeout,
and locking mechanisms prevent multiple processes from creating the
same base instance.
- …
> build(deps): bump craft-providers to 1.19.2

- pyproject.toml
-----
Snaps injected from the host will have their base snap injected into the instance.
> build(deps): bump craft-providers to 1.20.0

- craft_application/commands/__init__.py
- craft_application/commands/base.py
- craft_application/commands/lifecycle.py
- craft_application/util/__init__.py
- craft_application/util/callbacks.py
- tests/unit/commands/test_base.py
- tests/unit/commands/test_lifecycle.py
This creates a version of commands that can be modified by the application by registering parser fillers, prologues and epilogues. Additionally, it makes the lifecycle commands versions of these.
This is needed to support charmcraft's craft-application changeover, but is kept in draft until I can test it with charmcraft.
-----
> feat: extensible commands

- craft_application/util/error_formatting.py
- tests/unit/util/test_error_formatting.py
I'm unclear whether this would be considered a 'breaking change' since we do have several app-level tests that would need changing. I'm guessing not?
-----
This makes tracking the field names easier.
See: https://github.com/canonical/rockcraft/pull/440/files#r1417818696
> fix: quote field names in error messages

- craft_application/application.py
- craft_application/errors.py
- pyproject.toml
- tests/unit/test_application.py
Solve a race condition issue when creating dir under pyxdg.
Notice that `cache_dir` is now return `Path` not `str`.
Fixes: #167
> fix: use platformdirs replace pyxdg for cache path

- craft_application/application.py
- tests/unit/test_application.py
This allowed applications to register their own plugins beside the default plugins when initializing the app. Defined in `_get_app_plugins()`.
This also allowed app to ondemond register plugins by call `app.register_plugins(plugins)`.
> feat(plugins): support register plugins

- craft_application/errors.py
- craft_application/services/lifecycle.py
- tests/unit/services/test_lifecycle.py
Support use the following environment variables to control the parrallel build count:
Use
`<appname>_PARALLEL_BUILD_COUNT`
`CRAFT_PARALLEL_BUILD_COUNT`
to set to a fixed value.
Use
`<appname>_MAX_PARALLEL_BUILD_COUNT`
`CRAFT_MAX_PARALLEL_BUILD_COUNT`
to set to a dynamic value based on cpu count and max value.
By default it will use the current CPU count value to the parrallel build count.
Fixes: https://github.com/canonical/craft-application/issues/180
> feat: support control parallel build count from env

- craft_application/services/__init__.py
- craft_application/services/request.py
- craft_application/util/__init__.py
- craft_application/util/paths.py
- pyproject.toml
- tests/conftest.py
- tests/integration/services/test_request.py
- tests/unit/services/test_request.py
- tests/unit/util/test_paths.py
This service wraps Requests and adds some convenience functions methods. It's used by the remote build service, but can be used any time one might need requests.
-----
> feat: request service

- .github/renovate.json5
- craft_application/remote/git.py
- pyproject.toml
- tests/unit/remote/test_git.py
Drive-by: stop renovate from trying to update pygit2
-----
> build: broaden pygit2 dependency to include 1.14

- craft_application/models/constraints.py
- tests/unit/models/test_constraints.py
This was always supposed to be allowed. Found while updating snapcraft.
-----
> fix: allow project names to start with multiple digits

- craft_application/remote/git.py
This is a (manual) cherry-pick of commit 375553d6fc15 from snapcraft, with minor updates to make the comments more generic.
This gist of the fix is that pygit2 tries to initialize certificate locations at import-time, and when the application is running as a snap the certs are located in a non-standard (core-based) directory.
-----
> fix(remote-build): set a known path to cacerts

- craft_application/models/grammar.py
- pyproject.toml
- tests/unit/test_grammar.py
Parts are optional in charmcraft.yaml.
-----
> fix: make GrammarAwareProject accept no parts

- craft_application/models/project.py
- tests/unit/models/test_project.py
Pydantic 1.x seemingly root-validates using both file alias and name,
leading to inconsistent behavior. This should address the issue for
now, but the issue warrants further investigation.
-----
> fix(models): address adopt-info validation by name

- craft_application/services/remotebuild.py
- tests/unit/services/test_remotebuild.py
Launchpad doesn't error out if you try to create a token that expired in the past. Using non-timezone-aware datetime object in a timezone behind UTC can cause this.
-----
> fix(launchpad): use timezone-aware expiry time

- craft_application/application.py
- craft_application/commands/base.py
- tests/unit/test_application.py
-----
Design discussion on this said it was better to remove the options in commands that needed this and enforce a command either needing or not needing a project.
This essentially reverts #213 , but leaves the extra tests that are still relevant.
> feat!: remove optional project commands

- craft_application/application.py
- craft_application/errors.py
- craft_application/services/lifecycle.py
- craft_application/util/__init__.py
- craft_application/util/platforms.py
- pyproject.toml
- tests/conftest.py
- tests/integration/services/test_lifecycle.py
- tests/integration/services/test_service_factory.py
- tests/integration/test_application.py
- tests/unit/services/test_lifecycle.py
- tests/unit/test_application.py
This commit updates the LifecycleService to make use of the project's build plan when running. This specially affects destructive mode, where:
- Trying to run a build plan with no items is a (new) error;
- Trying to run a build plan with multiple items is a (new) error;
Note that although some forms of the "clean" command are also performed destructively, in this case we don't use the build plan. The rationale for this is:
- The lifecycle's local clean is always the same, regardless of target arch;
- Trying to define a build plan item via e.g. "appname clean --build-for=x" looks non-sensical (why define a "build-for" if I want to "clean"), and from a user's perspective calling "appname clean --destructive-mode" should just cleanup whatever was built previously.
-----
> feat!: use the build plan on LifecycleService

- craft_application/services/lifecycle.py
- tests/conftest.py
- tests/unit/services/test_lifecycle.py
Add methods to the lifecycle service to retrieve the list of pull
assets and primed stage packages from a given part. These can be
used to generate manifests of processed content.
-----
> feat(lifecycle): get pull assets and primed stage packages

- craft_application/services/provider.py
- tests/integration/services/test_provider.py
- tests/unit/services/test_provider.py
This provides two things:
1. Forwards proxy variables to the provider.
2. Provides an example for how an application can forward additional variables.
Fixes #258 (CRAFT-2579)
-----
> feat: pass environment variables to the instance.

- craft_application/application.py
Removes `build_for` and `platform` from `Application._configure_services()`
This will break any application that implements _configure_services and any service that expects these.
The new methodology is to pass the build plan to a service and use that.
-----
> feat(application)!: make configure_services not take parameters

- craft_application/errors.py
- craft_application/services/lifecycle.py
- tests/unit/services/test_lifecycle.py
The Lifecycle service will now check whether the build's base (as stored in the BuildInfo) matches the running environment. This doesn't affect managed runs (barring bugs), but is a change in behavior as we will no longer build, say, Ubuntu 22.04 artifacts on Fedora hosts in destructive mode.
We define "matches" here as this:
- If the build base is "devel", then only the systems have to match. For instance, you can build a "devel" Ubuntu-based artefact on any Ubuntu system, but not on a Fedora system.
- Otherwise, both the base's system and version must match, such that it is no longer possible to build ubuntu@22.04 on (say) ubuntu@20.04 systems.
Fixes #154
-----
> feat(lifecycle)!: don't build on incompatible bases

- craft_application/services/package.py
In line with _extra_yaml_transform(), add _extra_project_updates() as the place where subclasses can perform domain-specific updates to the Project when priming. The use-case here is to support Snapcraft's "parse-info" feature.
-----
> feat(package): add a point to do tool-specific updates

- craft_application/util/yaml.py
- tests/unit/util/test_yaml.py
When non-ASCII in the data, the entire text is escaped, especially in description.
> fix(yaml): allow use unicode in yaml

- craft_application/application.py
The full build plan could be used by remote build, so keep it in the project.
> feat(project): keep the full build plan for later use

- craft_application/application.py
- tests/unit/test_application.py
If a CraftError (or subclass) is raised when running the application, use its return code.
Credit for finding this bug goes to @syu-w 
-----
> fix(application): return the correct error code

- craft_application/application.py
- tests/integration/data/valid_projects/grammar/src/on-amd64-to-amd64/hello.txt
- tests/integration/data/valid_projects/grammar/src/on-amd64-to-arm64/hello.txt
- tests/integration/data/valid_projects/grammar/stderr
- tests/integration/data/valid_projects/grammar/testcraft.yaml
- tests/unit/test_application.py
The problem this commit addresses is this: Consider the following snippet:
```
parts:
hello-world:
plugin: dump
source:
- on amd64 to arm64: src/on-amd64-to-arm64
- on amd64 to armhf: src/on-amd64-to-armhf
```
... what should happen if the command `toolname clean --destructive-mode` is executed? Currently it breaks, because the grammar is not processed without an explict target arch (provided directly through the "--build-for" parameter or indirectly via the "--platform" one). This is at least inconvenient, and goes against the guideline we adopted for cleaning projects with multiple infos on the build-plan (accept the "wrong" config and remove the files).
There is no obvious, perfect answer here because at the stage that the grammar is currently processed we don't know yet what kind of …
> feat: always process the project's grammar

- craft_application/application.py
- craft_application/errors.py
- tests/unit/test_application.py
Filter plans based on `platform`, `build-on`, and `build-for`.
Use `platform` if it matched `build-for`
There is an API change that `_filter_plan` now need `host_arch` parameter, which can be used in remote builds.
Fixes: #254
> feat(platforms): support --build-for to select platform

- craft_application/application.py
- tests/integration/test_application.py
- tests/unit/test_application.py
This fixes an inconsistency between the command and the global flag as now both use the emitter to print the version.
-----
> fix(app): always "emit" version message

- craft_application/application.py
The motivation here is Snapcraft: it needs a way to provide a default command
(pack), but we explicitly do not want to support this at the craft-application
level.
> feat(app): provide a way to customize the Dispatcher 

- craft_application/application.py
- tests/unit/test_application.py
Use `CRAFT_VERBOSITY_LEVEL` to set log emitter level. If the level is invaild, default to BRIEF and continue.
> fix(log): allows set logging verbosity level from env

- craft_application/application.py
- craft_application/services/provider.py
- tests/unit/services/test_provider.py
- tests/unit/test_application.py
The log emitter paused too early that not logging the command it runs in the managed mode.
> fix(log): keep log emitter running until the run managed

- craft_application/launchpad/models/project.py
- craft_application/services/remotebuild.py
- tests/conftest.py
- tests/integration/conftest.py
- tests/integration/services/test_remotebuild.py
- tests/unit/services/test_remotebuild.py
This allows a command to set a user-provided project for remote build.
No protections are set up around this.
-----
> feat(remote-build): allow a user-provided project

- craft_application/remote/git.py
- craft_application/services/remotebuild.py
- tests/unit/services/test_remotebuild.py
> fix(remote-build): minor edge cases found with snapcraft

- craft_application/application.py
- craft_application/models/__init__.py
- craft_application/models/project.py
- craft_application/services/provider.py
- tests/conftest.py
- tests/unit/models/test_project.py
- tests/unit/services/test_lifecycle.py
- tests/unit/services/test_provider.py
- tests/unit/services/test_service_factory.py
- tests/unit/test_application.py
-----
Upstream `build-base` `devel` validation for all *craft applications.  This draft treats `devel` as the devel base, but I will update this to ~~26.04 before this PR can land~~ 24.10 when it is available.
Downstream integrations:
- https://github.com/canonical/charmcraft/pull/1634
- https://github.com/canonical/snapcraft/pull/4721
- https://github.com/canonical/rockcraft/pull/532
Fixes #298 
(CRAFT-2675)
> feat!: validate devel bases

- craft_application/application.py
- tests/unit/test_application.py
-----
Same as #316 but targeting `hotfix/2.6`.  The other PR got automatically closed and could not be re-opened after I deleted the `hotfix/2.5` branch.
`extra_yaml_transforms` should be applied before grammar because an application may add advanced grammar.
LP#2061603
(CRAFT-2817)
> fix: apply yaml transforms before grammar

- craft_application/remote/utils.py
-----
I've been hitting this bug when I run `tox run -m lint` in one terminal and `pytest` in another.  It causes the remote-build unit tests to occasionally fail when reading short-lived files in `craft-application/.tox/`, when it should be hashing the pytest temp directory.
> fix(remote): hash the project directory

- craft_application/application.py
- craft_application/models/project.py
- tests/conftest.py
- tests/integration/data/build-secrets/testcraft.yaml
- tests/integration/data/invalid_projects/build-error/testcraft.yaml
- tests/integration/data/valid_projects/adoption/testcraft.yaml
- tests/integration/data/valid_projects/basic/testcraft.yaml
- tests/integration/data/valid_projects/environment/testcraft.yaml
- tests/integration/data/valid_projects/grammar/testcraft.yaml
- tests/unit/models/project_models/full_project.yaml
- tests/unit/models/test_project.py
- tests/unit/services/test_lifecycle.py
- tests/unit/services/test_service_factory.py
- tests/unit/test_application.py
- tests/unit/util/invalid_yaml/unhashable.yaml-invalid
-----
This is a partial revert of 'aeae554 feat!: validate devel bases (#302)'.
The base validation from #302 has not been reverted, but there is now a default implementation for `Project._providers_base()` such that applications do not need to subclass the Project model.
The default naming convention for bases is `name@channel`.  Examples:
- `ubuntu@24.04`
- `ubuntu@devel`
- `almalinux@9`
Charmcraft is the only public application that can use this default `_providers_base()`.  
A default BuildPlanner will come in a subsequent PR.
(CRAFT-2824)
> revert: abstract Project class and `_providers_base()`

- craft_application/grammar.py
- craft_application/models/__init__.py
- craft_application/models/grammar.py
- tests/unit/models/test_grammar.py
- tests/unit/test_application.py
-----
Another grammar-related fix.
This is caused by [this](https://github.com/canonical/craft-application/pull/296/files#diff-1ef92b4ea98b9954fdb242a2697c47c5e275c45e703e54995980b2307da3187aR81) line augmenting data for non-grammar keywords.
It was causing errors like this:
```
Bad snapcraft.yaml content:
- value is not a valid list (in field 'parts.gnome-calculator.meson-parameters')
Full execution log: '/root/.local/state/snapcraft/log/snapcraft-20240429-201308.751985.log'
```
My solution is not to process grammar for non-grammar keywords.
> fix: do not process non-grammar keywords

- craft_application/application.py
- craft_application/services/lifecycle.py
- tests/unit/services/test_lifecycle.py
- tests/unit/test_application.py
-----
As raised in Matrix ([source](https://matrix.to/#/!GGqzbFAUQprdPgYYCM:ubuntu.com/$5CJQkAjgqbNn48zcF06HS8a0_0cjfogVCA_BDFi7XZE?via=ubuntu.com&via=matrix.org&via=kde.org)), `_extra_yaml_transforms` needs to occur before evaluating project variables.
For example, snapcraft will expand extensions in `_extra_yaml_transforms` and some extensions add project variables to the yaml.
Fixes https://github.com/canonical/snapcraft/issues/4771
> fix: apply yaml transforms first

- craft_application/application.py
- tests/integration/data/valid_projects/environment/testcraft.yaml
- tests/integration/test_application.py
- tests/unit/test_application.py
-----
As raised in Matrix ([source](https://matrix.to/#/!GGqzbFAUQprdPgYYCM:ubuntu.com/$ZP99NnFr-54yU3HEmz_LtWcaNtp8oxgHJ4pnix1uvNQ?via=ubuntu.com&via=matrix.org&via=kde.org)), `BUILD_FOR` variables aren't evaluated correctly because the `build-for` arch was not passed to craft-parts.
Builds on #334, so review last 2 commits only.
Fixes https://github.com/canonical/snapcraft/issues/4770
> fix: use `build-for` when evaluating project variables

- craft_application/application.py
- craft_application/commands/__init__.py
- craft_application/commands/base.py
- craft_application/commands/lifecycle.py
- tests/unit/commands/test_base.py
- tests/unit/commands/test_lifecycle.py
-----
Two things:
1. Refactors the LifecycleCommands classes in a slightly more organized way without changing any existing commands.  This is required for snapcraft to define its own `Pack` command with minimal duplicated code (https://github.com/canonical/snapcraft/pull/4794)
2. Add a `needs_project` property, which can determine if a project needs to be loaded based on the provided arguments.
Fixes https://github.com/canonical/snapcraft/issues/4769
(CRAFT-2861)
> feat: add `needs_project` property

- craft_application/application.py
- craft_application/remote/git.py
- pyproject.toml
> Some fixes to unbreak main

- craft_application/launchpad/models/project.py
- craft_application/launchpad/models/recipe.py
- craft_application/util/__init__.py
- craft_application/util/retry.py
- tests/unit/launchpad/test_launchpad.py
- tests/unit/services/test_remotebuild.py
- tests/unit/util/test_retry.py
Builds on top of #352, only the last commit is new.
This commit changes the retry() strategy: instead of sleeping a constant
3 seconds between attempts, each attempt sleeps twice as much as the previous
one (starting at 2 seconds). There is a cap of 5 attempts, so that the call
to retry can sleep() for at most 2+4+8+16+32 = 62 seconds.
> feat: exponential backoff for launchpad retries

- craft_application/services/remotebuild.py
- tests/unit/services/test_remotebuild.py
-----
Use the full project name in log files.
Fixes https://github.com/canonical/snapcraft/issues/4781
> fix(remotebuild): use full project name in log files

- craft_application/application.py
> chore: accept a Sequence

- craft_application/application.py
- tests/unit/test_application.py
The correct location to add craft-parts Features is a bit tricky:
- it must happen soon enough that things that happen early have the correct features enabled. For example, building the default command groups takes into account whether overlays are enabled;
- it must happen late enough that the craft-cli logging support has already been set-up.
Therefore, provide a method that Application subclasses can override to enable their features, and the Application itself takes care of calling it at the correct time.
-----
> feat: add a method to enable craft-parts Features

- craft_application/application.py
- craft_application/models/project.py
- craft_application/services/lifecycle.py
- craft_application/services/remotebuild.py
- docs/explanation/build-plans.rst
- docs/explanation/index.rst
- docs/reference/index.rst
- docs/reference/platforms.rst
- tests/integration/data/valid_projects/build-for-all/stderr
- tests/integration/data/valid_projects/build-for-all/testcraft.yaml
- tests/unit/models/test_project.py
- tests/unit/services/test_lifecycle.py
- tests/unit/services/test_remotebuild.py
- tests/unit/test_application.py
-----
Allows `build-for: [all]` in a platform definition.  When this is defined, no other platforms may be defined.
Related to https://github.com/canonical/snapcraft/issues/4854
Fixes #360
(CRAFT-3016)
> feat: accept build-for: [all] in platforms

- .github/workflows/release-publish.yaml
This is a partial revert of 0115c28629; apparently actions/checkout's "fetch-tags" property is broken and gives errors at checkout time.
Ref: https://github.com/actions/checkout/issues/1467
-----
> ci: fix checkout of tag in release workflow

- docs/howto/index.rst
- docs/howto/partitions.rst
-----
Add howto guide for using partitions.
You could argue that some of this content should really go into `craft-parts` documentation, but I would respond that doing that would make the document less useful.
(CRAFT-3068)
> docs: add howto for using partitions

- craft_application/application.py
- craft_application/util/__init__.py
- craft_application/util/docs.py
- tests/conftest.py
- tests/unit/test_application.py
- tests/unit/util/test_docs.py
This commit adds two new features:
- An util.render_doc_url() which creates a versioned url given an url with a `{version}` placeholder and a version value;
- Support for passing a rendered base url to the Emitter's init(), so that helper documentation links in error messages can contain the correct version (instead of the default readthedocs "stable" or "latest").
Fixes #368
-----
> feat: render versions in doc urls

- craft_application/services/remotebuild.py
- tests/unit/services/test_remotebuild.py
-----
Craft Application should push tags to Launchpad so that applications can derive versions from git tags.
source: 
- https://matrix.to/#/!GGqzbFAUQprdPgYYCM:ubuntu.com/$EpLRd25TPvDcrTxIVTcvHQsT6XJ-_BVrYMX0-Y2p980?via=ubuntu.com&via=matrix.org&via=kde.org
- https://github.com/canonical/pebble/pull/450
> fix(remotebuild): push git tags to launchpad

- tests/integration/services/test_provider.py
Mantic is no longer supported in craft-providers
-----
> chore: drop mantic from provider test

- tests/integration/services/test_lifecycle.py
The Mozilla team PPA updated its signing key recently. See: https://launchpad.net/~mozillateam/+archive/ubuntu/ppa See also: https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=index&search=0x738BEB9321D1AAEC13EA9391AEBDF4819BE21867
-----
> fix(tests): update mozilla keyring

- pyproject.toml
This removes using the tox-provided pyright venv
-----
> chore(lint): set user-provided pyright venv

- craft_application/models/constraints.py
- pyproject.toml
- tests/unit/models/test_constraints.py
Instead of having distributed license check in apps, we should provide a valid way of generic license check.
Application that utilizes `pydantic` v2 may opt-in for this validation in it's code
> feat: add SpdxLicenseStr and ProprietaryLicenseStr

- craft_application/services/provider.py
- tests/unit/services/test_provider.py
If the app isn't running from a snap, default to using the stable channel for the snap store snap, with an option to change channels using the CRAFT_SNAP_CHANNEL environment variable.
-----
> fix: allow using a snap from the snap store

- tests/conftest.py
- tests/integration/conftest.py
- tests/integration/test_application.py
- tests/unit/commands/test_base.py
- tests/unit/commands/test_lifecycle.py
- tests/unit/conftest.py
- tests/unit/git/test_git.py
- tests/unit/launchpad/conftest.py
- tests/unit/launchpad/models/test_base.py
- tests/unit/models/test_project.py
- tests/unit/remote/conftest.py
- tests/unit/remote/test_utils.py
- tests/unit/services/conftest.py
- tests/unit/services/test_lifecycle.py
- tests/unit/services/test_provider.py
- tests/unit/services/test_remotebuild.py
- tests/unit/services/test_service_factory.py
- tests/unit/test_application.py
- tests/unit/test_secrets.py
- tests/unit/util/test_retry.py
- tests/unit/util/test_snap_config.py
Run using `ruff check --fix`
-----
> style(lint): fix ruff 0.6.0 linting errors

- craft_application/application.py
- craft_application/errors.py
- tests/unit/test_application.py
This fix addresses cases like, for example, a project that only builds on `amd64` being built on `riscv64`. Previously the call to run_managed() would loop over the (empty) build plan and then finish "successfully". This new version will raise an EmptyBuildPlanError indicating to the user that they should check the project's 'platforms' declaration and the command-line parameters.
Fixes #225
-----
> fix: fail managed runs if the build plan is empty

- craft_application/commands/lifecycle.py
- tests/unit/commands/test_lifecycle.py
`--shell` and `--shell-after` are implemented for a) consistency with the other lifecycle commands, and b) because it makes sense to want to inspect the build environment at packing time, considering that there are packing-related steps, like writing the metadata file, that the users don't have a way to inspect otherwise (short of examining the final artefact).
`--debug` is improved to actually shell into the build environment when the packing itself failed, as opposed to the previous behavior of only debugging failures that happen during the lifecycle steps.
Fixes #430
-----
> feat: support shell/shell-after and debug in 'pack'

- craft_application/models/project.py
- tests/unit/models/test_project.py
This is a fix for https://github.com/canonical/charmcraft/issues/1874
The spec (ST105) allows `<list-of-arch> | <arch>` in both build-on and build-for on all craft apps. This change makes the Platform model accept a string value, but doesn't specify that in the schema. This means text editors using the schema will still suggest converting the build-on and build-for values to lists.
-----
> fix(platform): automatically vectorise architectures

- craft_application/__init__.py
- craft_application/_config.py
- craft_application/application.py
- craft_application/commands/lifecycle.py
- craft_application/launchpad/__init__.py
- craft_application/services/__init__.py
- craft_application/services/config.py
- craft_application/services/provider.py
- craft_application/services/remotebuild.py
- craft_application/services/service_factory.py
- pyproject.toml
- tests/conftest.py
- tests/integration/test_application.py
- tests/unit/services/test_config.py
- tests/unit/test_application.py
-----
Adds a service for handling application configuration. This service works as follows:
1. Uses application-specific environment variables
2. Uses general `CRAFT_*` environment variables
3. Uses application-provided configuration handlers
4. Uses snap configuration (if the app is installed as a snap)
5. Falls back to the default or errors if no default is set.
> feat: add a configuration service

- craft_application/models/base.py
- tests/unit/models/test_base.py
As seen in:
https://github.com/canonical/snapcraft/issues/4978 https://github.com/canonical/snapcraft/issues/5017
-----
> fix(models): coerce numbers to strings by default

- docs/reference/changelog.rst
-----
#450 hasn't been released yet.  I need it for https://github.com/canonical/snapcraft/issues/5017.
> fix(models): coerce numbers to strings by default (#450)

- craft_application/application.py
This allows applications to override the inner run logic, with the end goal of capturing application specific exceptions and raise appropriate ones for Craft Application to handle.
Without the logic split, overriding run to capture exceptions is virtually impossible as the run method holds a generic Exception handler.
-----
> chore: factor run logic outside of try block

- .github/workflows/tests.yaml
-----
Related: https://github.com/canonical/charmcraft/pull/1888#discussion_r1754963336
> ci: use the default version of lxd for integration tests

- craft_application/application.py
- craft_application/services/provider.py
- tests/unit/services/test_provider.py
- tests/unit/test_application.py
- tests/unit/test_application_fetch.py
This is necessary because the fetch-service needs visibility on *all* assets
downloaded during a build, so pre-existing instances that might already have
existing items cannot be re-used.
There are two commits: the first one adds the feature to wipe existing instances,
and the second one uses said feature when the fetch-service integration is enabled.
Fixes #40
>  feat: wipe existing instances when using the fetch-service

- craft_application/services/provider.py
- tests/unit/services/test_provider.py
-----
Inject snaps into the build environment using their aliased name.
I tested and confirmed this works with the reproducer in https://github.com/canonical/snapcraft/issues/4683.
However, I tested with a locally built snap, so it had no assertions.  The secondary failure in craft-providers with [`snap ack`](https://github.com/canonical/snapcraft/issues/4683#issuecomment-2344242230) will probably start occurring when testing with a signed snap from the store.
The craft-providers fix is probably changing [this line](https://github.com/canonical/craft-providers/blob/262978901d49e5c16668d8f0bc251b185837cee9/craft_providers/actions/snap_installer.py#L262) to `snap_name.split('_')[0]`.  
Fixes #411
> fix: inject aliased snaps into build environment

- craft_application/fetch.py
- tests/unit/test_fetch.py
Set it to shutdown after 5 minutes of no live sessions.
-----
> feat: set the fetch-service to idle shutdown

- craft_application/application.py
- craft_application/services/provider.py
- docs/reference/changelog.rst
- tests/unit/services/test_provider.py
- tests/unit/test_application.py
> chore: merge 4.2.3 to main

- craft_application/application.py
- craft_application/commands/lifecycle.py
- craft_application/errors.py
- craft_application/util/__init__.py
- craft_application/util/pro_services.py
- tests/conftest.py
- tests/unit/commands/test_lifecycle.py
- tests/unit/test_application.py
-----
This PR contains changes to add Ubuntu Pro argument to craft-applications allowing pro services to be specified for lifecycle commands. Specified pro services are validated at run against uaclient.
> Rocks 1457 / Rocks 1458 - Add Ubuntu Pro argument to craft-applications

- craft_application/remote/errors.py
- craft_application/remote/git.py
- docs/reference/changelog.rst
- tests/unit/git/test_git.py
- tests/unit/remote/test_errors.py
- tests/unit/remote/test_git.py
- tests/unit/remote/test_utils.py
-----
1. Refactor `RemoteBuild` errors to subclass `CraftError`
2. Slight changes to how remote build error are presented (moving information from `details` to `brief`)
3. Release notes for 4.2.4
Unblocks https://github.com/canonical/snapcraft/issues/4908
(CRAFT-3101)
> refactor: subclass remote-build errors from CraftError

- craft_application/commands/lifecycle.py
- docs/reference/changelog.rst
- tests/unit/test_application.py
This brings 'clean' closer to parity with the other lifecycle commands, and is useful for cases where we want to wipe one of the managed instances, but not all of them.
Fixes #425
-----
> feat: support "--platform" for "clean"

- craft_application/fetch.py
- tests/unit/test_fetch.py
The value makes Go download directly from version-controlled repositories, instead of module proxies like the default https://proxy.golang.org. It's currently a requirement for the Go inspector.
-----
> feat: set GOPROXY=direct in fetch-service runs

- craft_application/application.py
- craft_application/commands/lifecycle.py
- craft_application/fetch.py
- craft_application/services/fetch.py
- tests/integration/services/test_fetch.py
- tests/unit/commands/test_lifecycle.py
- tests/unit/services/test_fetch.py
- tests/unit/test_application_fetch.py
- tests/unit/test_fetch.py
'--use-fetch-service' now takes a mandatory argument defining the type of session to use: "strict" or "permissive".
Fixes #487
-----
> feat: allow strict/permissive fetch-service sessions

- pyproject.toml
-----
The relevant requests bug has been fixed, and this combines with upstream changes to let us use a newer requests.
> build(deps): loosen requests dependency

- craft_application/commands/lifecycle.py
- craft_application/services/fetch.py
- tests/unit/services/test_fetch.py
By "mark" we mean:
- hide the command-line option from pack's help;
- if enabled, warn that this integration is still in development.
Fixes #488
-----
> feat: mark the fetch-service integration as experimental

- docs/index.rst
- pyproject.toml
This replaces the diataxis grid with a list-table. https://docutils.sourceforge.io/docs/ref/rst/directives.html#list-table
Needed because the update to canonical-sphinx caused doc builds to fail and this was how they fixed it for themselves. https://github.com/canonical/canonical-sphinx/commit/e67baa49c47bb99319cfb720ff0964dbed6795eb
-----
> fix(docs): fix docs for canonical-sphinx 0.2

- craft_application/application.py
- craft_application/commands/lifecycle.py
- tests/unit/test_application_fetch.py
This is more in line with other "enabling" parameters that we have. This is not a breaking change because this fetch-service integration hasn't been released yet.
-----
> chore: rename parameter to "--enable-fetch-service"

- craft_application/models/manifest.py
- craft_application/services/fetch.py
- tests/data/manifest/craft-manifest-expected.json
- tests/data/manifest/session-manifest-expected.yaml
- tests/data/manifest/session-report.json
- tests/unit/models/test_manifest.py
- tests/unit/services/test_fetch.py
This PR is split over two commits; the first one augments the model to hold the rejection info, and the second one actually reports that info.
----
When creating the Craft manifest the FetchService will now also print a report
of those dependencies that were rejected by the fetch-service. This includes
the dependencies' urls and the list of rejection reasons.
Fixes #507
> feat: report fetch-service rejections

- craft_application/application.py
- craft_application/commands/base.py
- docs/reference/changelog.rst
- pyproject.toml
- tests/unit/commands/test_base.py
- tests/unit/test_application.py
This lets commands be able to always rely on `self.config` existing, even when running `fill_parser()` for help output.
Fixes #530
-----
> feat: pass the app_config to pre_parse_args()

- craft_application/application.py
- craft_application/fetch.py
- craft_application/services/fetch.py
- docs/reference/changelog.rst
- tests/integration/services/test_fetch.py
- tests/unit/test_application.py
- tests/unit/test_fetch.py
Add some steps under the "Configuring fetch-service integration :: " progress, to give some feedback that things are happening without all of the noisy output from Apt.
Fixes #536
-----
> fix: cleanup UI for fetch-service-related commands

- craft_application/application.py
- craft_application/commands/init.py
- craft_application/commands/lifecycle.py
- docs/reference/changelog.rst
- tests/integration/test_application.py
- tests/unit/test_application.py
-----
Allows Snapcraft to override default commands like the `InitCommand` and `PackCommand` without a hacky override ([source](https://github.com/canonical/snapcraft/pull/5129/files#r1813199559)).
- Applications can add a command to a `CommandGroup` where craft-application already provides a default command with the same name.  The application's command will replace the default command. 
- `CommandGroup.ordered` is no longer discarded.
- The Lifecycle CommandGroup is ordered.
- If an application registers multiple CommandGroups with the same group name, they will not be merged.
- I'm OK with this change because it is an odd thing to do, no applications do it, and I would consider it an incorrect way to use craft application.
(CRAFT-3543)
> feat(application): merge commands within groups

- .github/workflows/tests.yaml
- craft_application/fetch.py
- docs/reference/changelog.rst
- tests/unit/test_fetch.py
> chore: use 'candidate' fetch-service

- craft_application/application.py
- craft_application/util/yaml.py
- docs/reference/changelog.rst
- tests/conftest.py
- tests/integration/test_application.py
- tests/unit/test_application.py
-----
Adds documentation links in general help messages and command help messages.
> feat: add documentation link in help messages

- craft_application/application.py
-----
This PR fixes a bug where pro services validation would be skipped in destructive mode if no parameter to --pro was given.
> Fix: _check_pro_requirement function to not ignore empty ProServices set

- .readthedocs.yaml
It sets explicit version of Python for RTD builder, as today's upgrade to `3.13` breaks ci, due to missing `pygit2` wheel.
>  ci(rtd): pin python version to 3.12 

- craft_application/services/config.py
Both mypy and pyright complain that the "field.default_factory()" call has too few arguments, even though its type is typing.Callable[[], Any]. It should be fixed soon, and in the meantime we can ignore the spurious error.
Ref: https://github.com/pydantic/pydantic/issues/10945
-----
> chore(lint): get around a Pydantic 2.10.x type bug

- .github/workflows/tests.yaml
- craft_application/fetch.py
- craft_application/services/fetch.py
- docs/reference/changelog.rst
- tests/integration/services/test_fetch.py
- tests/unit/services/test_fetch.py
- tests/unit/test_fetch.py
The issue with redirecting the fetch-service's output to a file via bash is this: as a strict snap, the fetch-service cannot inherit the file descriptors from the bash process if said process is spawned by a classic snap. This is the case when the integration is controlled by a snapped craft tool:
```
+----------------------------+        +-------------+
|(snapped) craft-tool -> bash| -----> |fetch-service|
+----------------------------+        +-------------+
```
The solution here is to pass the path to the logfile to the fetch-service itself through a new, recently implemented command-line option. We also print the path to the logfile when emitting the warning about the integration being experimental.
Refs:
- https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1849753
Fixes #550
-----
> fix: properly log the fetch-service's output

- tests/unit/services/test_provider.py
-----
Two particular tests would, down the line, run a check against `os.getenv("SNAP_INSTANCE_NAME")` and default to a known value if it was unset. If these tests were ran directly in a standard ("non-snapped") program, this was fine. However, when running it using a snapped program (in my case, snapped VS Code's integrated testing tools), `SNAP_INSTANCE_NAME` will be set to the name of that program (again, in my case, `code`). 
Since the known value was never assigned, the test could not know what string to look for, causing this test to fail.
To avoid this failure, this PR removes that potentially confusing environment variable before running the test.
> fix(test): remove env var set by snapped testing programs

- craft_application/application.py
- docs/reference/changelog.rst
- tests/integration/test_application.py
Allow persisting ordering in help, when commands are registered through `add_command_group` API.
Linter issues are unrelated (they're from `ruff` update), fixed in #580
> feat: add ordered to the add_command_group API

- craft_application/launchpad/models/recipe.py
The code in CharmRecipe is 99% artifact-type-agnostic; generalize it out so that we can provide more artifact types with little new code.
The first commit just "renames" the existing CharmRecipe to _StandardRecipe; the second commit then has the actual changes to generalize the class, with the concrete CharmRecipe implementation.
> refactor: extract common code from CharmRecipe

- tests/integration/commands/test_init.py
Since 3.12.8, argparse 'choices' are no longer quoted. Ref: https://github.com/python/cpython/pull/11776
-----
> fix(tests): fix a test broken in Python 3.12.8

- craft_application/launchpad/__init__.py
- craft_application/launchpad/launchpad.py
- craft_application/launchpad/models/__init__.py
- craft_application/launchpad/models/build.py
- craft_application/launchpad/models/recipe.py
- docs/reference/changelog.rst
- tests/unit/launchpad/models/test_recipe.py
- tests/unit/launchpad/test_launchpad.py
> feat(launchpad): add RockRecipe

- tests/integration/launchpad/test_anonymous_access.py
-----
https://api.staging.launchpad.net/devel/people has been unreachable and is preventing us from releasing craft-application.
> tests: xfail launchpad test

- .pre-commit-config.yaml
- craft_application/launchpad/models/code.py
- craft_application/secrets.py
- craft_application/util/logging.py
- craft_application/util/string.py
- pyproject.toml
-----
New ruff is flagging https://docs.astral.sh/ruff/rules/stdlib-module-shadowing/
Renaming these modules feels like an API breakage, so I added exceptions.
> chore: add exceptions for stdlib module shadowing

- .github/workflows/release-publish.yaml
-----
ghcr.io/pypa/gh-action-pypi-publish seems to only be available on amd64:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
([source](https://github.com/canonical/craft-application/actions/runs/12752890346/job/35543369150#step:4:13))
Also, I think it makes sense to build the wheel on amd64.
> ci: build and publish artifacts on amd64

- craft_application/application.py
- docs/reference/changelog.rst
- tests/unit/test_application.py
Encoded secrets leak in the logs of the host instance, when managed instance is about to run. If additionally subsequent process fails, value is printed again in the failure traceback.
As they're only encoded not encrypted we should take a precautions and hide those values from the user.
> fix: do not log encoded secrets

- craft_application/launchpad/launchpad.py
- craft_application/launchpad/models/base.py
- craft_application/launchpad/models/recipe.py
- craft_application/services/remotebuild.py
- tests/unit/launchpad/test_launchpad.py
- tests/unit/services/conftest.py
- tests/unit/services/test_remotebuild.py
-----
Fixes a bug where the remote-builder would create a public repository and recipe, even when the project is private.
This is a backward-compatible change, but raises a deprecation warning if a project could be public.
I tested with snapcraft and can confirm the recipe and repo are private.
Fixes #614
(CRAFT-3984)
> fix(launchpad): use the project's privacy for repos and recipes

- craft_application/commands/remote.py
We don't have a --status argument and we don't want to implement one, so this just removes it from the overview text.
Fixes #620
CRAFT-4028
-----
> fix: remove --status from remote-build overview

- craft_application/commands/remote.py
This stops the remote builder from trying to clean up after a timeout.
It also removes where it talks about a `--build-id` option that doesn't exist.
Fixes #618
Fixes #619
CRAFT-4040
CRAFT-4025
-----
> fix(remote-build): don't cleanup after a timeout

- .github/workflows/tests.yaml
- .pre-commit-config.yaml
- .readthedocs.yaml
- craft_application/fetch.py
- craft_application/grammar.py
- craft_application/launchpad/launchpad.py
- craft_application/launchpad/models/base.py
- craft_application/launchpad/models/code.py
- craft_application/launchpad/models/recipe.py
- craft_application/models/manifest.py
- craft_application/secrets.py
- craft_application/services/config.py
- craft_application/services/remotebuild.py
- craft_application/util/logging.py
- craft_application/util/string.py
- docs/reference/changelog.rst
- pyproject.toml
- tests/data/manifest/session-report.json
- tests/integration/commands/test_init.py
- tests/integration/services/test_fetch.py
- tests/unit/launchpad/test_launchpad.py
- tests/unit/models/test_manifest.py
- tests/unit/services/conftest.py
- tests/unit/services/test_fetch.py
- tests/unit/services/test_remotebuild.py
- tests/unit/test_fetch.py
-----
* Cherry-picks #615 and 6 ci/lint-related commits
* Add a changelog entry for 4.4.1
Unblocks https://github.com/canonical/snapcraft/issues/5221
(CRAFT-4035)
> docs(changelog): add entry for 4.4.1

- craft_application/application.py
- pyproject.toml
- tests/unit/test_app_plugins.py
> fix: at plugin load time, emitter is not yet initialized

- tests/unit/models/test_project.py
- uv.lock
Error message has changed in `craft-platforms` 0.6.0, which makes CI to fail with it.
I haven't changed minimal required version in `pyproject.toml` (it's still `>=0.5.0`) as API was left intact.
> chore: update craft-platforms to 0.6.0

- craft_application/application.py
- tests/conftest.py
- tests/integration/test_application.py
- tests/unit/services/test_config.py
- tests/unit/test_application.py
This should make testing the Application more straightforward, as we're always in debug mode when we run tests (so `run()` raises exceptions that would otherwise become InternalErrors).
Already caught a test issue :-)
---
> test(fixtures): always enter debug mode for tests

- craft_application/application.py
- craft_application/pytest_plugin.py
- docs/conf.py
- docs/reference/changelog.rst
- docs/reference/index.rst
- docs/reference/pytest-plugin.rst
- pyproject.toml
- tests/conftest.py
- tests/integration/test_application.py
- tests/unit/conftest.py
- tests/unit/services/test_config.py
- tests/unit/test_application.py
- tests/unit/test_pytest_plugin.py
---
This adds a pytest plugin for craft-application, with several fixtures. The fixtures are documented on a [new reference page](https://canonical-craft-application--645.com.readthedocs.build/en/645/reference/pytest-plugin.html).
This is a breaking change because debug_mode is an auto-used fixture, any tests that rely on production mode will break.
> feat!(test): add a pytest plugin

- tests/integration/services/test_service_factory.py
- tests/integration/test_application.py
> test: remove deprecation warnings during test runs

- craft_application/services/fetch.py
- craft_application/services/service_factory.py
---
This makes the ServiceFactory no longer a dataclass. It's only a dataclass for historical reasons around the old way of registering services, but this is no longer necessary.
Requires #653
> refactor(ServiceFactory): de-dataclass the ServiceFactory 

- craft_application/fetch.py
- docs/reference/changelog.rst
- tests/unit/test_fetch.py
Increase timeout in `fetch-service` request as response in `0.1` may not always be achievable.
(CRAFT-4121)
> fix(fetch): increase timeout in requests

- craft_application/application.py
- craft_application/services/lifecycle.py
- craft_application/services/project.py
- docs/conf.py
- docs/reference/services/project.rst
- partitioncraft/services/project.py
- partitioncraft/templates/simple/partitioncraft.yaml.j2
- snap/snapcraft.yaml
- spread.yaml
- tests/conftest.py
- tests/integration/services/test_project.py
- tests/integration/services/test_service_factory.py
- tests/unit/conftest.py
- tests/unit/services/test_lifecycle.py
- tests/unit/services/test_project.py
- tests/unit/services/test_service_factory.py
- tests/unit/util/test_yaml.py
> feat!(ProjectService): allow the ProjectService to work with Imagecraft

- Makefile
- craft_application/application.py
- craft_application/commands/lifecycle.py
- craft_application/services/fetch.py
- craft_application/services/provider.py
- snap/snapcraft.yaml
- spread.yaml
- tests/conftest.py
- tests/integration/services/test_fetch.py
- tests/integration/services/test_provider.py
- tests/unit/commands/test_lifecycle.py
- tests/unit/services/test_fetch.py
- tests/unit/services/test_provider.py
- tests/unit/test_application.py
- tests/unit/test_application_fetch.py
---
Requires https://github.com/canonical/craft-application/pull/674
CRAFT-4163
> feat!: hybrid commands!

- craft_application/commands/lifecycle.py
- craft_application/fetch.py
- craft_application/services/buildplan.py
- testcraft/services/package.py
- tests/spread/testcraft/init-pack/task.yaml
- tests/spread/testcraft/pack-empty-plan/task.yaml
- tests/spread/testcraft/pack-empty-plan/testcraft.yaml
- tests/spread/testcraft/pack-multi/task.yaml
- tests/spread/testcraft/pack-multi/testcraft.yaml
- tests/unit/commands/test_lifecycle.py
- tests/unit/conftest.py
- tests/unit/services/test_buildplan.py
- tests/unit/services/test_lifecycle.py
Fixes this:
```yaml
platforms:
platform1:
build-on: [amd64]
build-for: [amd64]
platform2:
build-on: [amd64, arm64]
build-for: [arm64]
```
-> (error comes from the managed instance, not the host)
```
Multiple builds match the current platform: 'platform1' and 'platform2'.
Recommended resolution: Check the "--platform" and "--build-for" parameters.
```
---
> fix(commands/lifecycle): Pass the correct platform and build-for

- craft_application/errors.py
- craft_application/services/project.py
- docs/reference/changelog.rst
- tests/conftest.py
- tests/unit/services/test_project.py
Specify a project generation error and use it instead of a generic
runtime error when configuring and generating the prime project.
Fixes #705 
---
> fix!(services/project): use project generation error

- craft_application/commands/lifecycle.py
- docs/reference/changelog.rst
- tests/spread/testcraft/init-pack/task.yaml
- tests/unit/commands/test_lifecycle.py
- tests/unit/conftest.py
> fix: only run post prime in the process that ran the lifecycle

- spread.yaml
arm support was recently added causing conflict
---
> ci: lock to 24.04 amd64 image on google backend

- craft_application/application.py
- docs/reference/changelog.rst
This adds capturing of httpx logs to the log file to all apps by default. This is irrelevant if httpx is not used, but allows capturing request information from craft-store.
---
> feat(Application): capture httpx logs by default

- Makefile
- craft_application/application.py
- craft_application/models/__init__.py
- craft_application/models/platforms.py
- craft_application/models/project.py
- craft_application/models/spread.py
- craft_application/util/yaml.py
- pyproject.toml
- tests/integration/models/invalid_testcraft/platforms-build-for.yaml
- tests/integration/models/invalid_testcraft/platforms_short.yaml
- tests/integration/models/test_project_schema.py
- tests/integration/models/valid_testcraft/minimal.yaml
- tests/integration/models/valid_testcraft/platforms.yaml
- tests/unit/models/test_project.py
- uv.lock
This adds a PlatformDict class that behaves as a standard dictionary, but allows pydantic to model it and its schema correctly. The implementation is in a generic class (GenericPlatformsDict) that allows overriding of both the Platform type (if an application needs to modify its Platform model) and the keys that can be used as shorthands.
Demo in Rockcraft: https://github.com/canonical/rockcraft/pull/862
Fixes #688
CRAFT-4421
---
> feat(models): make the Platforms schema and processing work the same

- craft_application/application.py
- craft_application/git/_git_repo.py
- craft_application/models/spread.py
- docs/reference/changelog.rst
- tests/unit/git/test_git.py
Fix inconsistent output originating that could be affected by local user settings for `GitRepo.remote_contains` , so discovery is predictable.
> fix(git): read remotes without formatting in remote_contains

- craft_application/services/testing.py
- docs/reference/changelog.rst
- tests/spread/testcraft/test-cmd/task.yaml
- tests/unit/services/test_testing.py
When invoking the `test` command, don't run spread in verbose
mode to reduce output noise.
---
> chore(services/testing): reduce spread verbosity level

- craft_application/services/testing.py
- docs/reference/changelog.rst
- tests/unit/services/test_testing.py
Pause the emitter and disable stream capture when running the test
command with `--shell`, `--shell-after` or `--debug`. This allows
terminal interaction with the spread shell, but the spread output is
not sent to the craft application log.
---
> fix(testing): handle spread interactive shell

- craft_application/application.py
- docs/reference/changelog.rst
I should have removed this in 5.0 but overlooked it, so we're stuck with it until the next major release. It's essentially dead code though.
Removal PR for 6.0 is at https://github.com/canonical/craft-application/pull/762
---
> fix: mark Application._set_global_environment as deprecated

- craft_application/services/provider.py
- docs/reference/changelog.rst
These were supposed to have been forwarded by default but never were.
---
> fix(ProviderService): forward the parallel build count vars

- craft_application/commands/lifecycle.py
- docs/reference/changelog.rst
- tests/spread/testcraft/test-cmd/tests/spread/my-suite/my-task/task.yaml
- tests/unit/commands/test_lifecycle.py
- tests/unit/conftest.py
When running the `test` command, create the output artifact in the
standard output location instead of moving it to the spread
subdirectory.
Fixes #752
---
> fix(testing): don't change the output artifact location

- craft_application/models/project.py
- docs/reference/changelog.rst
This allows subclasses to easily add additional validation for parts.
See https://github.com/pydantic/pydantic/discussions/11523
(I don't see any)
(they both fail but on different files)
> feat(models): expose Part type

- .github/workflows/qa.yaml
---
This doesn't prevent us from using self-hosted runners for testing on other architectures, but our guidance is to use the free runners if possible.
> ci: switch test runs to free GitHub public runners

- craft_application/application.py
- craft_application/models/platforms.py
- craft_application/services/buildplan.py
- craft_application/services/project.py
- tests/conftest.py
- tests/unit/services/test_buildplan.py
- tests/unit/services/test_project.py
This modifies the ProjectService such that it's compatible with multi-base platforms definitions. AppMetadata gets a flag to register whether the app supports multi-base platforms (defaulting to False). If a user uses multi-base platforms when an app doesn't support it, they get an error message to that effect.
---
> feat(ProjectService): make the ProjectService compatible with multi-base

- craft_application/commands/lifecycle.py
- craft_application/services/lifecycle.py
- craft_application/services/package.py
- spread.yaml
- tests/spread/testcraft/test-cmd/task.yaml
- tests/spread/testcraft/test-cmd/testcraft.yaml
- tests/unit/commands/test_lifecycle.py
This changes the test command to pack and test all packable platforms. Note that it is out of scope as to whether the tests are valid to run. For example, a cross-compiled riscv64 binary might not be executable if tested on an amd64 machine, but we will still be running the tests, which will likely fail.
---
> feat(TestCommand): pack and test all packable platforms

- craft_application/services/proxy.py
- tests/unit/services/test_proxy.py
---
Fixes a bug where the proxy service would configure the proxy for apt, even if apt isn't available.
Follow-up from https://github.com/canonical/craft-application/pull/823#discussion_r2231392840
> fix(ProxyService): check if apt is available before configuring

- craft_application/services/state.py
- docs/reference/changelog.rst
- tests/unit/services/test_state.py
---
Gives the group read/write permission to state dir, when running with LXD as root.
This is needed due to https://github.com/canonical/craft-providers/pull/780, which sets uid and gid mapping separately.
Tested in https://github.com/canonical/craft-application/pull/835
> fix(StateService): add g+rwx to the state dir

- craft_application/models/spread.py
- docs/reference/changelog.rst
- tests/spread/testcraft/test-cmd/spread.yaml
Also check if the craft backend has type "craft" before processing
it and convert to the real spread backend type.
---
> fix(testing): verify craft backend type

- craft_application/services/provider.py
- docs/reference/changelog.rst
- tests/unit/services/test_provider.py
---
Bumps the compatibility tag in craft-application to prevent the reuse of instances created before the State service by updating the Provider service’s compatibility tag.
> fix(provider): bump compatibility tag

- craft_application/grammar.py
- docs/reference/changelog.rst
- pyproject.toml
- tests/unit/services/test_project.py
- uv.lock
---
Fixes https://github.com/canonical/craft-grammar/issues/124
CRAFT-4743
> fix: raise error on duplicate keys in processed dicts
