canonical/craft-application

- .github/workflows/tests.yaml
- craft_application/__init__.py
- pyproject.toml
- tox.ini
> meta: update metadata, incl. some dependencies

- craft_application/app.py
- tests/unit/test_app.py
> app: add AppMetadata data class for holding info about the app

- .github/workflows/tests.yaml
> ci: cache python packages

- craft_application/__init__.py
- craft_application/app.py
- craft_application/errors.py
- craft_application/parts.py
- tests/conftest.py
- tests/integration/test_nothing.py
- tests/integration/test_parts.py
- tests/unit/test_errors.py
- tests/unit/test_parts.py
> parts: add PartsLifecycle support

- craft_application/__init__.py
- craft_application/services/__init__.py
- craft_application/services/base.py
- craft_application/services/lifecycle.py
- tests/integration/services/test_lifecycle.py
- tests/unit/services/test_lifecycle.py
- tests/unit/test_errors.py
-----
The business logic for various commands will live in service classes, so the business logic for lifecycle should live there too.
> lifecycle: move PartsLifecycle to LifecycleService

- craft_application/commands/base.py
- craft_application/commands/lifecycle.py
- pyproject.toml
> deps: update craft-cli to 2.0.0

- pyproject.toml
- tox.ini
> deps: re-enable Python 3.12

- craft_application/application.py
- craft_application/errors.py
- craft_application/services/package.py
- craft_application/services/service_factory.py
- tests/conftest.py
- tests/integration/services/test_service_factory.py
- tests/integration/test_application.py
- tests/unit/conftest.py
- tests/unit/services/test_service_factory.py
> services: allow the service factory to be created before the project.

- pyproject.toml
> deps: freeze pydantic-yaml < 1.0

- craft_application/commands/lifecycle.py
- tests/unit/commands/test_lifecycle.py
-----
This avoids a long ticker on the message that the Lifecycle finished execution
> lifecycle: emit progress for packing

- craft_application/services/lifecycle.py
- tests/integration/services/test_lifecycle.py
- tests/unit/services/test_lifecycle.py
Also expand the text for human readable review with all variances available.
-----
> fix: improve lifecycle messages

- craft_application/errors.py
- craft_application/models/base.py
- craft_application/util/error_formatting.py
> ci(linters): address warnings

- craft_application/services/provider.py
- tests/unit/services/test_provider.py
Much like snaps, this is a list of distro-specific packages that should be installed in the instance created by the ProviderService.
-----
> feat(provider): expose a way to configure instance packages

- craft_application/commands/lifecycle.py
- craft_application/services/lifecycle.py
- tests/unit/commands/test_lifecycle.py
- tests/unit/services/test_lifecycle.py
> feat: implement --shell, shell-after, --debug

- craft_application/application.py
> feat: enable streaming in brief

- craft_application/commands/lifecycle.py
- tests/integration/test_application.py
- tests/unit/commands/test_lifecycle.py
This affects all lifecycle commands, including pack and clean.
Fixes #57
-----
> feat: support "--destructive-mode".

- craft_application/application.py
- craft_application/models/base.py
- tests/integration/data/valid_projects/environment/stdout
- tests/integration/data/valid_projects/environment/testcraft.yaml
- tests/integration/test_application.py
- tests/unit/models/test_project.py
- tests/unit/test_application.py
> feat: do variable expansion when loading project

- tests/integration/services/test_provider.py
> fix(test): fix provider integration tests

- HACKING.rst
- pyproject.toml
- tox.ini
-----
I've also made (and yanked) a "0.1.0" release on pypi.
> build: set metadata ready for pypi release

- pyproject.toml
This corresponds to how Starbase does it
-----
> fix(build): only package craft-application/*

- pyproject.toml
> test: add pytest marker for enable_features

- .github/workflows/tests.yaml
> build: separate unit and integration tests in CI

- craft_application/application.py
> feat: customise command config

- craft_application/application.py
- tests/unit/test_application.py
> feat: resolvable project path

- craft_application/application.py
- craft_application/util/__init__.py
- craft_application/util/logging.py
- tests/unit/util/test_logging.py
> feat: setup loggers utility function

- craft_application/application.py
- tests/unit/test_application.py
> fix: un-deprecate project attribute

- craft_application/services/lifecycle.py
- tests/unit/services/test_lifecycle.py
> feat: post-prime hook for LifecycleService

- .github/renovate.json5
- pyproject.toml
> ci(deps): prevent renovate from updating pydantic

- craft_application/misc/instance_bashrc
- craft_application/services/provider.py
- tests/integration/services/test_provider.py
- tests/unit/services/test_provider.py
This allowed to save some info and environment variable to help debug when needed.
> feat(provider): inject bashrc into instance

- craft_application/services/lifecycle.py
- craft_application/util/callbacks.py
- craft_application/util/yaml.py
- pyproject.toml
-----
All automatic except for the change to pyproject.toml
> style(black): update black to v24

- craft_application/models/project.py
- pyproject.toml
- tests/conftest.py
- tests/unit/models/test_project.py
- tests/unit/services/test_service_factory.py
- tests/unit/test_application.py
- tests/unit/test_errors.py
> style(typing): update pyright

- tests/conftest.py
> test: skip overlay tests if fuse-overlayfs not installed.

- craft_application/application.py
- pyproject.toml
- tests/integration/test_application.py
- tests/unit/test_application.py
> feat!: project directory as an application attribute

- craft_application/launchpad/__init__.py
- craft_application/launchpad/errors.py
- craft_application/launchpad/launchpad.py
- craft_application/launchpad/models/__init__.py
- craft_application/launchpad/models/base.py
- craft_application/launchpad/models/build.py
- craft_application/launchpad/models/code.py
- craft_application/launchpad/models/project.py
- craft_application/launchpad/models/recipe.py
- craft_application/launchpad/util.py
- craft_application/services/lifecycle.py
- craft_application/services/provider.py
- pyproject.toml
- tests/integration/launchpad/conftest.py
- tests/integration/launchpad/test_anonymous_access.py
- tests/unit/launchpad/models/test_base.py
- tests/unit/launchpad/test_util.py
This client is a wrapper around launchpadlib that provides a unified interface. It's heavily inspired by the Launchpad wrapper used in snapcraft's most recent remote build, but with tweaks to make it more generic.
-----
> feat: launchpad client

- pyproject.toml
> chore(deps): update ruff and its configuration

- .github/workflows/tests.yaml
- HACKING.rst
- pyproject.toml
- tox.ini
> build: use ruff from snap

- craft_application/launchpad/models/code.py
- tests/unit/launchpad/models/test_code.py
> fix: putting a target on a new git repo is optional

- craft_application/launchpad/models/build.py
> fix: add launchpad build types and states

- craft_application/launchpad/launchpad.py
- craft_application/launchpad/models/code.py
- tests/integration/launchpad/conftest.py
- tests/integration/launchpad/test_anonymous_access.py
- tests/unit/launchpad/test_launchpad.py
Also adds integration tests
-----
> fix: update rendering of git repository paths

- craft_application/services/remotebuild.py
> fix(remotebuild): create the launchpad instance correctly

- craft_application/application.py
- tests/unit/test_application.py
Snapcraft needs these to render the extensions
> feat!(app): forward build-on and build-for

- craft_application/launchpad/launchpad.py
- tests/integration/launchpad/test_anonymous_access.py
- tests/unit/launchpad/test_launchpad.py
> fix: make launchpad client always create relevant files

- craft_application/launchpad/models/__init__.py
- craft_application/launchpad/models/base.py
- craft_application/launchpad/models/build.py
- craft_application/launchpad/models/distro.py
- craft_application/services/remotebuild.py
> feat(launchpad): add models to support charm building

- pyproject.toml
> build(deps): make pygit2 a required dependency

- tests/unit/launchpad/test_util.py
-----
The blessing and curse of hypothesis: it'll randomly find new issues!
> fix(test): don't test mangled names in getattrs

- craft_application/services/provider.py
- tests/unit/services/test_provider.py
> fix(provider): install package-repositories deps

- craft_application/launchpad/models/project.py
> fix: handle multiple types of Launchpad error when getting projects

- HACKING.rst
> docs(test): clarify what is needed for unit tests dependency

- craft_application/models/constraints.py
-----
So nobody has to repeat the digging @sergiusens had to do earlier.
> docs(constraints): explain where we get the version string regex

- .github/renovate.json5
> ci: update renovate config to match starbase

- craft_application/launchpad/models/recipe.py
- tests/unit/launchpad/test_launchpad.py
> fix(launchpad): retry create recipes if launchpad error

- craft_application/__init__.py
> fix: use correct package for version

- craft_application/application.py
- craft_application/services/lifecycle.py
- tests/conftest.py
- tests/unit/services/test_lifecycle.py
- tests/unit/test_application.py
> feat: expose partitions to the lifecycle service

- craft_application/services/remotebuild.py
- tests/unit/services/conftest.py
- tests/unit/services/test_remotebuild.py
> fix(remote): don't crash if the repo exists

- pyproject.toml
- tests/integration/launchpad/test_anonymous_access.py
-----
This is a temporary workaround to fix CI before we get around to #306
> tests: disable broken integration test

- craft_application/grammar.py
- craft_application/models/grammar.py
- pyproject.toml
- tests/integration/data/valid_projects/grammar/testcraft.yaml
- tests/unit/test_application.py
This allows use `- on X to Y: values` in all parts.
Needs: https://github.com/canonical/craft-grammar/pull/17
> feat(grammar): enable grammar-aware for all PartSpec

- craft_application/application.py
- craft_application/services/lifecycle.py
- craft_application/util/repositories.py
- tests/conftest.py
- tests/unit/services/test_lifecycle.py
- tests/unit/services/test_repositories.py
- tests/unit/test_application.py
> chore: merge 'hotfix/2.6' back into 'main'

- craft_application/grammar.py
- tests/integration/data/valid_projects/grammar/testcraft.yaml
- tests/unit/test_application.py
-----
Fixes https://github.com/canonical/snapcraft/issues/4764
> fix: allow a mix of strings and dicts for grammar

- craft_application/grammar.py
- craft_application/models/__init__.py
- craft_application/models/grammar.py
- craft_application/services/lifecycle.py
- tests/integration/data/valid_projects/grammar/testcraft.yaml
- tests/unit/models/test_grammar.py
- tests/unit/services/test_lifecycle.py
- tests/unit/test_application.py
Plus a bonus commit to address issues found by latest ruff
> chore(merge): merge 'hotfix/2.6' into 'main'

- craft_application/errors.py
> style: fix typo in error message

- craft_application/commands/lifecycle.py
- tests/unit/commands/test_lifecycle.py
-----
This ended up being extremely simple after landing #340.
Tested via https://github.com/canonical/snapcraft/pull/4797
> fix(PackCommand): remove 'parts' argument

- craft_application/application.py
- craft_application/remote/git.py
- tests/unit/test_application.py
> feat: allow commands to accept multiple platforms

- .yamllint.yaml
- craft_application/application.py
- craft_application/models/__init__.py
- craft_application/models/project.py
- craft_application/remote/git.py
- craft_application/util/__init__.py
- craft_application/util/platforms.py
- pyproject.toml
- tests/conftest.py
- tests/integration/data/build-secrets/testcraft.yaml
- tests/integration/data/invalid_projects/build-error/testcraft.yaml
- tests/integration/data/valid_projects/adoption/testcraft.yaml
- tests/integration/data/valid_projects/basic/testcraft.yaml
- tests/integration/data/valid_projects/environment/testcraft.yaml
- tests/integration/data/valid_projects/grammar/testcraft.yaml
- tests/integration/test_application.py
- tests/unit/commands/test_base.py
- tests/unit/models/project_models/basic_project.yaml
- tests/unit/models/project_models/full_project.yaml
- tests/unit/models/test_project.py
- tests/unit/services/test_lifecycle.py
- tests/unit/test_application.py
- tests/unit/util/test_platforms.py
-----
- Add a `Platform` model
- Implement the default `BuildPlanner`
(CRAFT-2824)
> feat: add Platform model and default BuildPlanner

- craft_application/services/provider.py
> fix: ensure provider is available before launching

- docs/reference/changelog.rst
- docs/reference/index.rst
-----
Prep for `2.9.0` release.
Adds the changelog to the documentation per [starbase](https://github.com/canonical/starbase/blob/main/HACKING.rst#changelog) conventions.
Preview here: https://canonical-craft-application--366.com.readthedocs.build/en/366/reference/changelog.html
> docs: add changelog

- .github/workflows/release-publish.yaml
- docs/reference/changelog.rst
- docs/reference/index.rst
Two commits, one for each task
> Add release workflow and 2.9.0 changelog

- docs/reference/changelog.rst
-----
Unblocks https://github.com/canonical/snapcraft/issues/4889
Unblocks https://github.com/canonical/snapcraft/pull/4892
> docs(changelog): add 3.1.0 release notes

- docs/howto/partitions.rst
> documentation pickups from #371

- docs/reference/changelog.rst
> docs(changelog): add 3.2.0 release notes

- craft_application/git/_git_repo.py
- tests/unit/git/test_git.py
It adds additional methods to the `GitRepo` for repository cloning and managing remotes configuration (creating, renaming and checking for the existence)
(CRAFT-3087)
> feat: add clone and remotes to GitRepo

- craft_application/services/provider.py
> fix(type): fix ProviderService.get_base annotation

- craft_application/application.py
- craft_application/models/__init__.py
- craft_application/models/base.py
- craft_application/models/constraints.py
- craft_application/models/grammar.py
- craft_application/models/metadata.py
- craft_application/models/project.py
- craft_application/services/lifecycle.py
- craft_application/util/error_formatting.py
- craft_application/util/snap_config.py
- pyproject.toml
- tests/integration/conftest.py
- tests/integration/services/test_lifecycle.py
- tests/integration/services/test_provider.py
- tests/integration/test_application.py
- tests/unit/commands/test_lifecycle.py
- tests/unit/models/test_base.py
- tests/unit/models/test_constraints.py
- tests/unit/models/test_project.py
- tests/unit/services/test_lifecycle.py
- tests/unit/test_application.py
- tests/unit/test_errors.py
- tests/unit/util/test_snap_config.py
-----
Failing tests are due to craft-grammar needing this merge: https://github.com/canonical/craft-grammar/pull/34
> build!: update to pydantic 2

- pyproject.toml
-----
Point craft-providers to `feature/2.0`.
> build(deps): point to craft-providers feature/2.0 branch

- docs/reference/changelog.rst
> docs: add 4.0.0 release to changelog

- craft_application/services/lifecycle.py
- tests/unit/conftest.py
- tests/unit/services/test_lifecycle.py
> feat(lifecycle): break out _get_build_for method

- pyproject.toml
-----
I did this manually because Renovate is creating the branches and then not creating the PRs. I think it's to do with the needed updates from starbase.
> build(deps): update development and build dependencies

- docs/reference/changelog.rst
> docs: add 4.1.0 changelog entry

- craft_application/errors.py
- craft_application/util/yaml.py
- tests/unit/test_errors.py
- tests/unit/util/test_yaml.py
> fix(yaml): wrap error message for YAML errors

- craft_application/errors.py
- craft_application/services/lifecycle.py
- tests/unit/services/test_lifecycle.py
> feat: tell the user which platforms matched when failing

- docs/reference/changelog.rst
-----
Add release notes for 4.1.1.
(CRAFT-3107)
> docs(changelog): add release notes for 4.1.1

- docs/reference/environment-variables.rst
- docs/reference/index.rst
> docs: add environment variables reference

- craft_application/errors.py
- tests/unit/test_errors.py
- tests/unit/util/test_yaml.py
-----
Fixes the information disappearing from #427. Thanks @mattculler for pointing this out.
> fix: provide more info in YAML errors

- craft_application/application.py
- craft_application/errors.py
- docs/reference/changelog.rst
- tests/unit/test_application.py
- tests/unit/test_errors.py
- tests/unit/util/test_yaml.py
> Cherry-pick fixes for 4.1.2 and add changelog

- craft_application/application.py
- craft_application/services/service_factory.py
- tests/unit/services/test_service_factory.py
> feat: replace ServiceFactory.set_kwargs with ServiceFactory.update_kwargs

- .pre-commit-config.yaml
> build(deps): update pre-commit hooks

- tests/integration/services/test_provider.py
- tests/unit/services/test_provider.py
> tests: re-enable almalinux tests

- tests/integration/test_application.py
> chore(test): put ids on some hard-to-trigger tests

- docs/reference/changelog.rst
> docs: add changelog for 4.2.0

- craft_application/models/base.py
- docs/reference/changelog.rst
- tests/unit/models/test_base.py
> chore: merge release 4.1.3 into main

- craft_application/models/base.py
- docs/reference/changelog.rst
- tests/unit/models/test_base.py
-----
cherry-picks the PR from 4.1.3 and adds a changelog entry.
> create release 4.2.1

- craft_application/application.py
- docs/reference/changelog.rst
> Release 4.2.2 with cherry-pick of #466

- craft_application/application.py
- docs/reference/changelog.rst
> chore: merge 4.2.2 to main

- craft_application/application.py
- docs/reference/changelog.rst
- tests/unit/test_application.py
> Config namespace fix and changelog update

- docs/howto/partitions.rst
- tox.ini
-----
Fix the docs to not tell users to reset Features, and to override Application method.  Also do some cleanup now that I've actually used partitions.
(CRAFT-3325)
> feat: update partitions docs

- craft_application/services/fetch.py
- tests/integration/services/test_fetch.py
- tests/unit/services/test_fetch.py
This PR builds on top of #476 - the relevant changes are contained on the last commit
-----
When running with the fetch-service integration enabled, the FetchService
service will generate a manifest file containing both metadata about the
packed artifact (from the project and the artifact itself) and about the
dependencies that were downloaded during the build (from the fetch-service
session report).
> feat: create the final craft manifest

- craft_application/remote/errors.py
- craft_application/remote/git.py
- docs/reference/changelog.rst
- tests/unit/git/test_git.py
- tests/unit/remote/test_errors.py
- tests/unit/remote/test_git.py
- tests/unit/remote/test_utils.py
-----
Merge 4.2.4 back into main
> chore(merge): 4.2.4 into main

- .github/workflows/security-scan.yaml
> ci: add security scanning job

- craft_application/services/config.py
- tests/unit/services/test_config.py
> fix(config): warn on snapctl errors

- craft_application/models/project.py
- craft_application/services/lifecycle.py
- pyproject.toml
- tests/integration/data/build-secrets/testcraft.yaml
- tests/integration/data/invalid_projects/build-error/testcraft.yaml
- tests/integration/data/valid_projects/adoption/testcraft.yaml
- tests/integration/data/valid_projects/basic/testcraft.yaml
- tests/integration/data/valid_projects/build-for-all/testcraft.yaml
- tests/integration/data/valid_projects/environment/testcraft.yaml
- tests/integration/data/valid_projects/grammar/testcraft.yaml
- tests/integration/test_application.py
- tests/unit/models/test_project.py
- tests/unit/services/test_lifecycle.py
Also warns about some pending deprecations.
-----
> feat: add craft-platforms compatibility methods

- docs/reference/changelog.rst
- pyproject.toml
> docs(changelog): release 4.2.5

- craft_application/services/config.py
- docs/reference/changelog.rst
- pyproject.toml
- tests/unit/services/test_config.py
> chore: merge 4.2.6 to main

- craft_application/launchpad/models/base.py
- craft_application/services/config.py
- pyproject.toml
> build(deps): update pyright

- docs/reference/changelog.rst
- pyproject.toml
> fix: loosen requests dependency

- docs/reference/changelog.rst
> docs: changelog for 4.3.0

- .github/workflows/release-publish.yaml
> chore(ci): generate release notes when publishing

- craft_application/commands/init.py
- craft_application/models/constraints.py
- craft_application/services/init.py
- docs/reference/changelog.rst
- tests/integration/commands/test_init.py
- tests/unit/commands/test_init.py
- tests/unit/services/test_init.py
> feat: improve name handling in 'init'

- docs/reference/changelog.rst
> docs: finish changelog for 4.5.0

- craft_application/commands/__init__.py
- craft_application/commands/other.py
- craft_application/commands/test.py
- craft_application/models/__init__.py
- craft_application/models/spread.py
- craft_application/services/__init__.py
- craft_application/services/service_factory.py
- craft_application/services/testing.py
- tests/integration/test_application.py
- tests/unit/commands/test_other.py
- tests/unit/test_application.py
Take a simplified version of spread.yaml supplied by the user, and
generate the full-fledged project file to be consumed by spread.
Fixes #560
-----
> feat(testing): process simplified spread.yaml

- .pre-commit-config.yaml
- craft_application/grammar.py
- pyproject.toml
> style(ruff): fix linting issues from ruff update

- craft_application/application.py
- craft_application/services/fetch.py
- craft_application/services/service_factory.py
- pyproject.toml
- tests/conftest.py
- tests/integration/services/test_service_factory.py
- tests/unit/conftest.py
- tests/unit/services/test_service_factory.py
- tests/unit/test_application.py
- tests/unit/test_application_fetch.py
-----
This is a semi-WIP PR for dynamic service registration. I'm requesting reviews now so we can discuss whether I'm taking the correct path. Lint issues are known and will be fixed; unit test issues are due to some changes to test fixtures that I will revert.
> feat(ServiceFactory): dynamic service registration

- pyproject.toml
Fixes #577
Linting issues fixed in #580 
-----
> build(deps) replace pytest-freezegun with pytest-freezer

- craft_application/commands/test.py
- craft_application/grammar.py
- craft_application/services/testing.py
Process the craft test spread.yaml file and generate a temporary
file with resolved testing backend. Execute spread on the generated
file.
-----
> feat(testing): execute spread on generated file

- craft_application/application.py
- craft_application/models/manifest.py
- docs/reference/changelog.rst
- tests/data/manifest/session-report.json
- tests/integration/services/test_fetch.py
- tests/unit/models/test_manifest.py
- tests/unit/services/test_fetch.py
- tests/unit/test_application.py
> chore: merge 4.8.2 to main

- .github/PULL_REQUEST_TEMPLATE.md
- docs/conf.py
- docs/reference/changelog.rst
-----
Same checklist addition as in https://github.com/canonical/craft-parts/pull/942
Same release link ignore as in https://github.com/canonical/craft-parts/pull/909/commits/67f1668b2fd4c14e348743e833ea9fec5e4d48ca
Also adds an entry for #615.
> docs: update changelog, add PR checklist item

- docs/reference/changelog.rst
> docs(changelog): prepare 4.8.3 release

- craft_application/__init__.py
- craft_application/application.py
- pyproject.toml
- tests/unit/conftest.py
- tests/unit/test_app_plugins.py
- tests/unit/test_application.py
-----
Allow applications to register plugins to modify library behavior.
(CRAFT-4018)
> feat: application plugins

- docs/reference/changelog.rst
-----
4.4.1 only cherry-picked commits that were already on `main`, so this PR only brings in a changelog.
> chore(merge): 4.4.1 into main

- docs/reference/changelog.rst
> docs(changelog): prepare 4.9.0 release

- craft_application/application.py
- craft_application/errors.py
- craft_application/services/lifecycle.py
- craft_application/util/pro_services.py
- tests/unit/commands/test_lifecycle.py
- tests/unit/test_application.py
---
The purpose of this PR is to introduce a preliminary check for --pro enabled builds to avoid commands on "devel" bases.
> Changes for RK042 - Guard against pro builds on "devel" bases  - 10/02/25

- docs/reference/changelog.rst
> docs: finalize entries for 4.10.0

- .github/workflows/spread.yaml
- craft_application/util/yaml.py
- partitioncraft/__init__.py
- partitioncraft/__main__.py
- partitioncraft/application.py
- partitioncraft/cli.py
- partitioncraft/services/__init__.py
- partitioncraft/services/package.py
- partitioncraft/services/project.py
- partitioncraft/services/provider.py
- partitioncraft/templates/simple/partitioncraft.yaml.j2
- snap/snapcraft.yaml
- spread.yaml
- testcraft/cli.py
- testcraft/services/__init__.py
- tests/spread/partitioncraft/init-pack/task.yaml
- tests/spread/testcraft/init-pack/task.yaml
- tests/unit/services/test_buildplan.py
- tests/unit/util/test_yaml.py
- uv.lock
---
This creates `partitioncraft`, a minimal app that uses partitions. It also adds it to the `testcraft` snap and runs a basic
lifecycle spread test for it.
Requires #666
> feat(test): create partitioncraft

- craft_application/services/project.py
> perf: cache project file path

- craft_application/models/project.py
- craft_application/services/buildplan.py
- craft_application/services/project.py
- tests/conftest.py
- tests/unit/services/test_project.py
---
Response to https://github.com/canonical/craft-application/pull/683#discussion_r2005973548
Only the [last two commits](https://github.com/canonical/craft-application/pull/686/files/ad587613b9718389617ed4da30da1ddd7927a589..1778987ba68bc895a33932caaaf26371b7b5e9b4) are this PR, the rest are #683.
> fix(ProjectService): better handling for invalid platforms

- craft_application/pytest_plugin.py
- docs/reference/changelog.rst
- docs/reference/pytest-plugin.rst
- docs/reference/services/project.rst
---
Includes suggestions from https://github.com/canonical/craft-application/pull/672
> docs: update docs for 5.0.0

- craft_application/commands/lifecycle.py
- craft_application/services/testing.py
- tests/unit/services/test_testing.py
> fix(TestingService): provide a better error if spread.yaml is missing

- craft_application/services/testing.py
- tests/unit/services/test_testing.py
> fix(TestingService): error better when we can't find spread

- docs/reference/changelog.rst
> docs(changelog): release 5.0.4

- craft_application/models/spread.py
- docs/reference/changelog.rst
- tests/unit/models/test_spread.py
> fix(SpreadBackend): accept string system models

- .github/.jira_sync_config.yaml
> ci: update Jira sync configuration

- craft_application/commands/lifecycle.py
- craft_application/services/testing.py
- docs/reference/changelog.rst
Report testing success and use better error message in case of testing
failure.
---
> fix(testing): improve testing messages

- craft_application/git/_git_repo.py
- docs/reference/changelog.rst
- tests/integration/git/test_git.py
- tests/unit/git/test_utils.py
Add possibility to read and store configuration values in repository via GitRepo object.
> feat(git): add API to modify repo configuration

- craft_application/models/constraints.py
---
* Update the name field so that it renders properly with Kitbash. The new description is modeled after [Snapcraft's name description](https://github.com/canonical/snapcraft/blob/main/snapcraft/models/project.py#L1290-L1292).
* Small fixes on other descriptions
> docs: update name description

- tests/integration/launchpad/test_anonymous_access.py
> test: don't run staging tests if the API is erroring

- pyproject.toml
- uv.lock
---
Spread tests are fixed in #784
> build(deps): replace oracular dev env with questing

- craft_application/services/provider.py
- tests/unit/services/test_provider.py
> fix(provider): don't pass null values or certain excluded values from config

- docs/reference/changelog.rst
---
Brings in 5.2.1 into main.
> chore(merge): 5.2.1 into main

- .pre-commit-config.yaml
- craft_application/commands/base.py
- craft_application/models/project.py
- craft_application/pytest_plugin.py
- craft_application/util/repositories.py
- pyproject.toml
- tests/unit/commands/test_lifecycle.py
- tests/unit/commands/test_remote.py
- tests/unit/conftest.py
- tests/unit/git/test_git.py
- tests/unit/models/test_constraints.py
- tests/unit/services/test_provider.py
- tests/unit/services/test_service_factory.py
- tests/unit/services/test_testing.py
---
Test failure is fixed in #804
> style: fix linting issues with ruff 0.12

- .github/workflows/release-publish.yaml
> ci: fix publishing workflow

- craft_application/services/lifecycle.py
- docs/reference/changelog.rst
- tests/unit/services/test_lifecycle.py
> Enable application overriding lifecycle action execution

- craft_application/application.py
- craft_application/fetch.py
- craft_application/services/__init__.py
- craft_application/services/config.py
- craft_application/services/fetch.py
- craft_application/services/provider.py
- craft_application/services/proxy.py
- craft_application/services/service_factory.py
- docs/reference/changelog.rst
- tests/integration/services/test_fetch.py
- tests/spread/testcraft/fetch-service-managed/task.yaml
- tests/spread/testcraft/fetch-service-managed/testcraft.yaml
- tests/unit/services/test_fetch.py
- tests/unit/services/test_provider.py
- tests/unit/services/test_proxy.py
- tests/unit/test_fetch.py
---
This PR splits out proxy-specific code from the fetch service into a new proxy service.  
Even though this PR adds a new service, it's a refactor because there are no behavioral changes.
(CRAFT-4576)
> refactor: add a proxy service

- common.mk
---
Cherry-picks the relevant Starbase commits to update make setup.
> fix: install system packages when running `make setup`

- craft_application/application.py
- craft_application/commands/lifecycle.py
- docs/reference/changelog.rst
- testcraft/application.py
- tests/conftest.py
> fix(pack): put a gate around skipping repack.

- craft_application/application.py
- craft_application/commands/lifecycle.py
- docs/reference/changelog.rst
- testcraft/application.py
- tests/conftest.py
> chore(merge): 'hotfix/5.6' into 'main'

- craft_application/services/state.py
- docs/reference/changelog.rst
- tests/unit/services/test_state.py
> chore(merge): 5.6.2 into main

- README.md
---
Code cov was able to redirect the to the correct url, but this PR corrects them anyway.
> docs: update code cov url

- docs/reference/changelog.rst
> docs(changelog): Release 5.7.0

- .github/workflows/spread.yaml
- craft_application/services/provider.py
- docs/reference/changelog.rst
- tests/unit/services/test_provider.py
> chore(merge): 5.6.5 into main

- craft_application/application.py
- craft_application/services/lifecycle.py
- craft_application/services/package.py
- craft_application/services/project.py
- docs/reference/changelog.rst
- pyproject.toml
- tests/conftest.py
- tests/integration/services/test_lifecycle.py
- tests/spread/witchcraft/project-vars/expected-metadata.yaml
- tests/spread/witchcraft/project-vars/task.yaml
- tests/spread/witchcraft/project-vars/witchcraft.yaml
- tests/unit/services/test_package.py
- tests/unit/services/test_project.py
- tests/unit/test_application.py
- uv.lock
- witchcraft/__init__.py
- witchcraft/application.py
- witchcraft/models/__init__.py
- witchcraft/models/metadata.py
- witchcraft/models/project.py
- witchcraft/services/package.py
- witchcraft/services/project.py
---
Allows setting nested project variables.
Depends on https://github.com/canonical/craft-parts/pull/1220
(SNAPCRAFT-1054)
> feat: support nested project variables

- craft_application/services/lifecycle.py
- docs/reference/changelog.rst
- tests/spread/testcraft/pack/bare-base/testcraft.yaml
- tests/spread/testcraft/pack/task.yaml
- tests/spread/testcraft/unset-adopt-info/task.yaml
- tests/spread/testcraft/unset-adopt-info/testcraft.yaml
- tests/unit/services/test_lifecycle.py
> fix(Lifecycle): don't cache the project

- craft_application/services/lifecycle.py
- docs/reference/changelog.rst
- tests/spread/testcraft/pack/bare-base/testcraft.yaml
- tests/spread/testcraft/pack/task.yaml
- tests/spread/testcraft/unset-adopt-info/task.yaml
- tests/spread/testcraft/unset-adopt-info/testcraft.yaml
- tests/unit/services/test_lifecycle.py
> chore(merge): 5.9.1 into main

- docs/reference/changelog.rst
- pyproject.toml
- uv.lock
> fix(launchpad): don't skip proxies

- docs/reference/changelog.rst
- pyproject.toml
- uv.lock
> chore: merge 5.10.2 to main

- docs/reference/commands/index.rst
---
Fixes an indentation issue that I accidentally suggested in my review of https://github.com/canonical/craft-application/pull/912.
> docs: fix indentation

- craft_application/util/error_formatting.py
- docs/reference/changelog.rst
- tests/unit/models/test_base.py
- tests/unit/models/test_project.py
- tests/unit/services/test_project.py
- tests/unit/test_errors.py
- tests/unit/util/test_error_formatting.py
- tests/unit/util/test_snap_config.py
> feat(errors): include input value on pydantic errors

- docs/reference/changelog.rst
> docs(changelog): backfill release links and add a template
